/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package casot1;
 
/**
 *
 * @author User001
 */
public class PersonitasResultado extends javax.swing.JFrame {
     private ListaPersonitas padre;
     private  Personita personitaSelec;

    /**
     * Creates new form PersonitasResultado
     */
    public PersonitasResultado() {
        initComponents();
    }

    public PersonitasResultado(ListaPersonitas padre, Personita personaSelec) {
        initComponents();
        this.padre = padre;
        this.personitaSelec = personaSelec;
        lblResultado.setText(personaSelec.getNombre());     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResultado = new javax.swing.JLabel();
        bttRegresar = new javax.swing.JButton();

        lblResultado.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblResultado.setText("Soy: Fabrizio Grosso");

        bttRegresar.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        bttRegresar.setText("Regresar");
        bttRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblResultado)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bttRegresar)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblResultado)
                .addGap(18, 18, 18)
                .addComponent(bttRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegresarActionPerformed
        this.padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttRegresar;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables

}
